NUM_LAGS = 30
NUM_EPCOHS = 10
BATCH_SIZE = 32
NUM_PERIDOS_TO_PREDICT = 3

TRAIN = 1
DONT_TRAIN = 0
TO_TRAIN_OR_NOT_TO_TRAIN = DONT_TRAIN

SAVE = 1
DONT_SAVE = 0
TO_SAVE_OR_NOT_TO_SAVE = DONT_SAVE
